version = 0.1.0
java_name = cascara.lang.markdown
maven_name = cascara-lang-markdown
group = io.github.qishr
title = Cascara Markdown
description = Cascara Markdown language processors.
url = https://qishr.github.io/javadoc/cascara.lang.markdown/
scm_url = https://github.com/qishr/cascara-lang-markdown
scm_conn = scm:git:https://github.com/qishr/cascara-lang-markdown.git
scm_dev_conn = scm:git:https://github.com/qishr/cascara-lang-markdown.git

org.gradle.configuration-cache = false


